name: wake
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  file_picker: ^5.0.1
  flutter_pdfview: ^1.2.3
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  dio: ^5.5.0+1
  provider: ^6.1.2
  intl: ^0.19.0
  animations: ^2.0.11
  fl_chart: ^0.68.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
